spring:
  application:
    name: department-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bdmicio
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        '[dialect]': org.hibernate.dialect.PostgreSQLDialect
        cache:
          '[use_query_cache]': false

  data:
    jpa:
      repositories:
        enabled: true

server:
  port: 8081
management:
   endpoints:
        web:
           exposure:
               include:*