server:
  port: 8278

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bdmicio
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

